-- MySQL Script generated by MySQL Workbench
-- Sat May 16 21:02:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET GLOBAL event_scheduler=ON;

-- -----------------------------------------------------
-- Schema expense_tracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema expense_tracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `expense_tracker` DEFAULT CHARACTER SET utf8 ;
USE `expense_tracker` ;

-- -----------------------------------------------------
-- Table `expense_tracker`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker`.`currency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `currency_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expense_tracker`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker`.`user` (
  `user_id` VARCHAR(32) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `ph_no` VARCHAR(15) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `dob` DATE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `currency_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `currency_id_fk_idx` (`currency_id` ASC) VISIBLE,
  CONSTRAINT `currency_id_fk`
    FOREIGN KEY (`currency_id`)
    REFERENCES `expense_tracker`.`currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expense_tracker`.`income_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker`.`income_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expense_tracker`.`monthly_income_source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker`.`monthly_income_source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(32) NOT NULL,
  `source_name` VARCHAR(100) NOT NULL,
  `amount` INT NOT NULL,
  `income_category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `income_source_cat_id_idx` (`income_category_id` ASC) VISIBLE,
  CONSTRAINT `is_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `expense_tracker`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `is_ic_id_fk`
    FOREIGN KEY (`income_category_id`)
    REFERENCES `expense_tracker`.`income_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expense_tracker`.`expense_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker`.`expense_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expense_tracker`.`monthly_bill_reminder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker`.`monthly_bill_reminder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bill_desc` VARCHAR(100) NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `expense_category_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `paid` TINYINT(1) NOT NULL,
  `deadline_date` INT(2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `bill_reminder_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `bill_reminder_expense_cat_idx` (`expense_category_id` ASC) VISIBLE,
  CONSTRAINT `br_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `expense_tracker`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `br_ec_id_fk`
    FOREIGN KEY (`expense_category_id`)
    REFERENCES `expense_tracker`.`expense_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expense_tracker`.`income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker`.`income` (
  `id` VARCHAR(32) NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `income_desc` VARCHAR(100) NOT NULL,
  `amount` INT NOT NULL,
  `date` DATE NOT NULL,
  `income_category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `income_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `income_category_id_fk_idx` (`income_category_id` ASC) VISIBLE,
  CONSTRAINT `income_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `expense_tracker`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `income_ic_id_fk`
    FOREIGN KEY (`income_category_id`)
    REFERENCES `expense_tracker`.`income_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expense_tracker`.`expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker`.`expense` (
  `id` VARCHAR(32) NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `expense_desc` VARCHAR(100) NOT NULL,
  `expense_category_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `expense_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `expense_category_id_idx` (`expense_category_id` ASC) VISIBLE,
  CONSTRAINT `expense_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `expense_tracker`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `expense_ec_id_fk`
    FOREIGN KEY (`expense_category_id`)
    REFERENCES `expense_tracker`.`expense_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expense_tracker`.`report_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker`.`report_statistics` (
  `id` INT NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `income_category_id` INT NULL,
  `expense_category_id` INT NULL,
  `month` VARCHAR(10) NOT NULL,
  `year` VARCHAR(10) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `income_category_id_fk_idx` (`income_category_id` ASC) VISIBLE,
  INDEX `expense_category_id_fk_idx` (`expense_category_id` ASC) VISIBLE,
  CONSTRAINT `income_category_id_fk`
    FOREIGN KEY (`income_category_id`)
    REFERENCES `expense_tracker`.`income_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `expense_category_id_fk`
    FOREIGN KEY (`expense_category_id`)
    REFERENCES `expense_tracker`.`expense_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `expense_category` (`category_name`)
VALUES ('Housing'),('Travel'),('Dining'),('Entertainment'),
('Electronics'),('Groceries'),('Clothing & Beauty Products'),
('Medical'),('Personal'),('Education'),('Gifts/Donations'),
('Household Items'),('Other');

INSERT INTO `income_category` (`category_name`)
VALUES ('Salary'),('Rent'),('Business Income'),
('Securities and Other Income'),('Gifts/Donations'),
('Other');

INSERT INTO `currency` (`currency_name`)
VALUES ('US Dollars'),('Euro'),('British Pound Sterling'),
('Indian Rupees'),('Japanese Yen'),('Canadian Dollars'),('Australian Dollars');

CREATE EVENT `monthly_bill_reminder_reset`
ON SCHEDULE EVERY '1' MONTH STARTS date_format(curdate(),'%Y-%m-01')
ON COMPLETION PRESERVE
DO UPDATE `monthly_bill_reminder` SET paid=0;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
